# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

include:
  - project: sysadmin/ci-utilities
    file:
      - /gitlab-templates/android.yml
      - /gitlab-templates/linux.yml
      - /gitlab-templates/freebsd.yml
      - /gitlab-templates/linux-qt6.yml
      - /gitlab-templates/freebsd-qt6.yml
      - /gitlab-templates/craft-android-arm32.yml
      - /gitlab-templates/craft-android-arm64.yml
      - /gitlab-templates/craft-android-x86-64.yml
      - /gitlab-templates/craft-android-appbundle.yml
