# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

include:
  - https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/android.yml
  - https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/linux.yml
  - https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/freebsd.yml
  # - https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/linux-qt6.yml
  # - https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/freebsd-qt6.yml
  # - https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/android-qt6.yml
  - https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/reuse-lint.yml
  - https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/flatpak.yml
  - https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/craft-android-arm32.yml
  - https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/craft-android-arm64.yml
  - https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/craft-android-x86-64.yml

signapk:
  stage: deploy
  when: manual
  image: invent-registry.kde.org/sysadmin/ci-images/android-qt515:latest
  tags:
    - Linux
  variables:
    GIT_STRATEGY: none
  interruptible: true
  needs:
    - craft_android_arm64
  before_script:
    - git clone https://invent.kde.org/kloecker/ci-services.git sftpnotary
    - cd sftpnotary
    - python3 -m venv .venv
    - . .venv/bin/activate
    - pip3 install -r requirements.txt
  script:
    - curl -O https://invent.kde.org/sysadmin/ci-utilities/-/raw/work/kloecker/signing-configs/signing/signapk.ini
    - python3 signapk.py -v --config signapk.ini $CI_PROJECT_DIR/.kde-ci-packages/*.apk
  artifacts:
    expire_in: 3 days
    when: always
    paths:
     - ".kde-ci-packages/"

signflatpak:
  stage: deploy
  when: manual
  image: invent-registry.kde.org/sysadmin/ci-images/android-qt515:latest
  tags:
    - Linux
  variables:
    GIT_STRATEGY: none
  interruptible: true
  needs:
    - flatpak
  before_script:
    - git clone https://invent.kde.org/kloecker/ci-services.git sftpnotary
    - cd sftpnotary
    - python3 -m venv .venv
    - . .venv/bin/activate
    - pip3 install -r requirements.txt
  script:
    - curl -O https://invent.kde.org/sysadmin/ci-utilities/-/raw/work/kloecker/signing-configs/signing/signflatpak.ini
    - python3 signflatpak.py -v --config signflatpak.ini $CI_PROJECT_DIR/${CI_PROJECT_NAME}.flatpak
  artifacts:
    expire_in: 3 days
    when: always
    paths:
     - "task*.log"
