# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

include:
  # - https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/android.yml
  # - https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/linux.yml
  # - https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/freebsd.yml
  # - https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/linux-qt6.yml
  # - https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/freebsd-qt6.yml
  # - https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/android-qt6.yml
  # - https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/reuse-lint.yml
  # - https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/flatpak.yml
  - https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/craft-android-arm32.yml
  - https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/craft-android-arm64.yml
  - https://invent.kde.org/sysadmin/ci-utilities/raw/master/gitlab-templates/craft-android-x86-64.yml

signapk:
  stage: deploy
  when: manual
  image: invent-registry.kde.org/sysadmin/ci-images/android-qt515:latest
  tags:
    - Linux
  variables:
    GIT_STRATEGY: none
    KDECI_CRAFT_SIGNAPK_CONFIG: $CI_PROJECT_DIR/ci-utilities/signing/signapk.ini
  interruptible: true
  needs:
    - craft_android_arm64
  before_script:
    - git clone --depth=1 https://invent.kde.org/sysadmin/ci-utilities --branch=work/kloecker/signing-configs
    - git clone --depth=1 https://invent.kde.org/sysadmin/ci-notary-service.git --branch=work/kloecker/signapk-check-signing-allowed
    # - cd ci-notary-service
    # - git checkout work/fdroid-publisher
    # - python3 -m venv .venv
    # - . .venv/bin/activate
    # - pip3 install -r requirements.txt
  script:
    - python3 ci-notary-service/signapk.py -v --config $KDECI_CRAFT_SIGNAPK_CONFIG $CI_PROJECT_DIR/.kde-ci-packages/*.apk
    # - cd ci-notary-service
    # - curl -O https://invent.kde.org/sysadmin/ci-utilities/-/raw/work/kloecker/signing-configs/signing/signapk.ini
    # - python3 signapk.py -v --config signapk.ini $CI_PROJECT_DIR/.kde-ci-packages/*.apk
  artifacts:
    expire_in: 3 days
    when: always
    paths:
     - ".kde-ci-packages/"

publishonfdroid:
  stage: deploy
  when: manual
  image: invent-registry.kde.org/sysadmin/ci-images/android-qt515:latest
  tags:
    - Linux
  variables:
    GIT_STRATEGY: none
  interruptible: true
  needs:
    - signapk
  before_script:
    - git clone --depth=1 https://invent.kde.org/sysadmin/ci-notary-service.git
    # - cd ci-notary-service
    # - git checkout work/fdroid-publisher
    # - python3 -m venv .venv
    # - . .venv/bin/activate
    # - pip3 install -r requirements.txt
  script:
    - cd ci-notary-service
    #- curl -O https://invent.kde.org/sysadmin/ci-utilities/-/raw/work/kloecker/signing-configs/signing/publishonfdroid.ini
    - echo '[SFTP]' >publishonfdroid.ini
    - echo 'Server = tinami.kde.org' >>publishonfdroid.ini
    - echo 'Username = signing' >>publishonfdroid.ini
    - echo 'BasePath = workspace/fdroidpublishing' >>publishonfdroid.ini
    - echo 'RsaKeyFile = env:KDECI_SECURE_SERVICES_KEY' >>publishonfdroid.ini
    - python3 publishonfdroid.py -v --config publishonfdroid.ini $CI_PROJECT_DIR/.kde-ci-packages/*.apk $CI_PROJECT_DIR/.kde-ci-packages/fastlane-*.zip
  artifacts:
    expire_in: 3 days
    when: always
    paths:
     - ".kde-ci-packages/task*.log"

# signflatpak:
#   stage: deploy
#   when: manual
#   image: invent-registry.kde.org/sysadmin/ci-images/android-qt515:latest
#   tags:
#     - Linux
#   variables:
#     GIT_STRATEGY: none
#   interruptible: true
#   needs:
#     - flatpak
#   before_script:
#     - git clone https://invent.kde.org/sysadmin/ci-notary-service.git
#     - cd ci-notary-service
#     - python3 -m venv .venv
#     - . .venv/bin/activate
#     - pip3 install -r requirements.txt
#   script:
#     - curl -O https://invent.kde.org/sysadmin/ci-utilities/-/raw/work/kloecker/signing-configs/signing/signflatpak.ini
#     - python3 signflatpak.py -v --config signflatpak.ini $CI_PROJECT_DIR/${CI_PROJECT_NAME}.flatpak
#   artifacts:
#     expire_in: 3 days
#     when: always
#     paths:
#      - "task*.log"
