# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

include:
  - project: sysadmin/ci-utilities
    file:
      - /gitlab-templates/android.yml
      - /gitlab-templates/linux.yml
      - /gitlab-templates/freebsd.yml
      - /gitlab-templates/linux-qt6.yml
      - /gitlab-templates/freebsd-qt6.yml
      - /gitlab-templates/android-qt6.yml
      - /gitlab-templates/reuse-lint.yml
      - /gitlab-templates/flatpak.yml
      - /gitlab-templates/craft-android-apks.yml
      # - /gitlab-templates/craft-android-qt6-apks.yml
