# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/kcoreaddons': '@stable'
    'frameworks/kconfig': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kcontacts': '@stable'
    'frameworks/kirigami': '@stable'
    'frameworks/knotifications': '@stable'
    'frameworks/kholidays': '@stable'
    'frameworks/karchive': '@stable'
    'frameworks/prison': '@stable'
    'libraries/kpublictransport': "@same"
    'libraries/kosmindoormap': "@same"
    'pim/kpkpass': '@same'
    'pim/kitinerary': '@same'
    'libraries/kosmindoormap': '@same'
    'pim/khealthcertificate': '@latest'

- 'on': ['Linux', 'FreeBSD']
  'require':
    'frameworks/kdbusaddons': '@stable'
    'frameworks/qqc2-desktop-style': '@stable'

- 'on': ['Linux']
  'require':
    'frameworks/networkmanager-qt': '@stable'
