# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux', 'FreeBSD', 'Windows', 'Android']
  'require':
    'frameworks/extra-cmake-modules': 'Frameworks/6.24'
    'frameworks/kcoreaddons': 'Frameworks/6.24'
    'frameworks/kconfig': 'Frameworks/6.24'
    'frameworks/ki18n': 'Frameworks/6.24'
    'frameworks/kcolorscheme': 'Frameworks/6.24'
    'frameworks/kcontacts': 'Frameworks/6.24'
    'frameworks/kirigami': 'Frameworks/6.24'
    'frameworks/kitemmodels': 'Frameworks/6.24'
    'frameworks/knotifications': 'Frameworks/6.24'
    'frameworks/kholidays': 'Frameworks/6.24'
    'frameworks/karchive': 'Frameworks/6.24'
    'frameworks/prison': 'Frameworks/6.24'
    'frameworks/kunitconversion': 'Frameworks/6.24'
    'libraries/kpublictransport': "@same"
    'libraries/kosmindoormap': "@same"
    'libraries/kirigami-addons': 'v1.11.0'
    'pim/kpkpass': '@same'
    'pim/kitinerary': '@same'
    'pim/khealthcertificate': '@same'
    'third-party/libquotient': '@latest'
    'third-party/qtkeychain': '@latest-kf6'
    'third-party/qcoro': '@latest'

- 'on': ['Linux', 'FreeBSD']
  'require':
    'frameworks/kdbusaddons': 'Frameworks/6.24'
    'frameworks/qqc2-desktop-style': 'Frameworks/6.24'
    'frameworks/kcrash': 'Frameworks/6.24'
    'frameworks/kio': 'Frameworks/6.24'
    'frameworks/kfilemetadata': 'Frameworks/6.24'
    'frameworks/kwindowsystem': 'Frameworks/6.24'

RuntimeDependencies:
- 'on': ['Linux']
  'require':
    'plasma/qqc2-breeze-style': 'master'
    'plasma/plasma-integration': 'master'
    'sdk/selenium-webdriver-at-spi': '@latest-kf6'

Options:
  require-passing-tests-on: [ 'Linux/Qt6', 'FreeBSD' ]
