# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux', 'FreeBSD', 'Windows', 'Android']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kcoreaddons': '@latest-kf6'
    'frameworks/kconfig': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/kcontacts': '@latest-kf6'
    'frameworks/kirigami': '@latest-kf6'
    'frameworks/kitemmodels': '@latest-kf6'
    'frameworks/knotifications': '@latest-kf6'
    'frameworks/kholidays': '@latest-kf6'
    'frameworks/karchive': '@latest-kf6'
    'frameworks/prison': '@latest-kf6'
    'frameworks/kunitconversion': '@latest-kf6'
    'libraries/kpublictransport': "@same"
    'libraries/kosmindoormap': "@same"
    'libraries/kirigami-addons': '@latest-kf6'
    'pim/kpkpass': '@same'
    'pim/kitinerary': '@same'
    'pim/khealthcertificate': '@same'
    'third-party/libquotient': '@latest'

- 'on': ['Linux', 'FreeBSD']
  'require':
    'frameworks/kdbusaddons': '@latest-kf6'
    'frameworks/qqc2-desktop-style': '@latest-kf6'
    'frameworks/kcrash': '@latest-kf6'
    'frameworks/kio': '@latest-kf6'
    'frameworks/kfilemetadata': '@latest-kf6'
    'frameworks/kwindowsystem': '@latest-kf6'

- 'on': ['Linux']
  'require':
    'frameworks/networkmanager-qt': '@latest-kf6'

Options:
  require-passing-tests-on: [ 'Linux', 'FreeBSD' ]
